# Generated by Django 3.2.14 on 2022-07-28 19:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAttend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('ticket', models.CharField(max_length=10)),
                ('qr_code', models.ImageField(blank=True, upload_to='media/qr_codes')),
                ('canceled', models.BooleanField(default=False)),
                ('entered', models.BooleanField(default=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'شرکت کننده کلاس حضوری',
                'verbose_name_plural': 'لیست شرکت کنندگان کلاس حضوری',
            },
        ),
        migrations.CreateModel(
            name='ClassCancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.IntegerField(unique=True)),
                ('ticket', models.CharField(max_length=10, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'فرد کنسل کننده کلاس حضوری',
                'verbose_name_plural': 'لیست کنسل کنندگان کلاس حضوری',
            },
        ),
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='capacity_counter', max_length=100)),
                ('counter', models.PositiveIntegerField(default=310, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(310)])),
            ],
            options={
                'verbose_name': 'ظرفیت کلاس حضوری',
                'verbose_name_plural': 'ظرفیت کلاس حضوری',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('description', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'نقد و انتقاد',
                'verbose_name_plural': 'نقد و انتقادات',
            },
        ),
        migrations.CreateModel(
            name='NoSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('ticket', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=2048)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'فرد بدون پشتیبان',
                'verbose_name_plural': 'لیست افرادی بدون پشتیبان',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.IntegerField(unique=True)),
                ('ticket', models.CharField(max_length=10, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'دانشجو دوره',
                'verbose_name_plural': 'لیست دانشجویان دوره',
            },
        ),
        migrations.CreateModel(
            name='SupporterSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('token', models.CharField(max_length=6)),
                ('satisfaction', models.BooleanField()),
                ('supporter', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('validate_status', models.BooleanField(default=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'نظرسنجی TA ها',
                'verbose_name_plural': 'نظرسنجی TA ها',
            },
        ),
        migrations.CreateModel(
            name='SupportSurveyCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_counter', models.PositiveIntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='web.students')),
            ],
            options={
                'verbose_name': 'تاریخچه محدودید ثبت نظر برای TA ها',
                'verbose_name_plural': 'تاریخچه محدودید ثبت نظر برای TA ها',
            },
        ),
    ]
