# Generated by Django 3.2.14 on 2022-07-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupporterSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('token', models.CharField(max_length=6)),
                ('supporter', models.IntegerField()),
                ('status', models.BooleanField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'نظرسنجی TA ها',
                'verbose_name_plural': 'نظرسنجی TA ها',
            },
        ),
        migrations.RenameModel(
            old_name='SupportSurveyHistory',
            new_name='SupportSurveyCounter',
        ),
    ]
