# Generated by Django 4.0.6 on 2022-07-26 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classattend',
            options={'verbose_name': 'شرکت کننده کلاس حضوری', 'verbose_name_plural': 'لیست شرکت کنندگان کلاس حضوری'},
        ),
        migrations.AlterModelOptions(
            name='classcancel',
            options={'verbose_name': 'فرد کنسل کننده کلاس حضوری', 'verbose_name_plural': 'لیست کنسل کنندگان کلاس حضوری'},
        ),
        migrations.AlterModelOptions(
            name='classinfo',
            options={'verbose_name': 'ظرفیت کلاس حضوری', 'verbose_name_plural': 'ظرفیت کلاس حضوری'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'نقد و انتقاد', 'verbose_name_plural': 'نقد و انتقادات'},
        ),
        migrations.AlterModelOptions(
            name='nosupport',
            options={'verbose_name': 'فرد بدون پشتیبان', 'verbose_name_plural': 'لیست افرادی بدون پشتیبان'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': 'دانشجو دوره', 'verbose_name_plural': 'لیست دانشجویان دوره'},
        ),
    ]
