# Generated by Django 3.2.14 on 2022-07-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classattend',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='classcancel',
            name='phone',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='nosupport',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='phone',
            field=models.BigIntegerField(unique=True),
        ),
    ]
