# Generated by Django 3.2.14 on 2022-07-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classcancel',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
