# Generated by Django 3.2.14 on 2022-08-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classattend',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=255),
        ),
    ]
