# Generated by Django 3.2.14 on 2022-08-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_classattend_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classcancel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='classcancel',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='classcancel',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
