# Generated by Django 3.2.14 on 2022-07-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20220723_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='classinfo',
            name='name',
            field=models.CharField(default='capacity_counter', max_length=100),
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='counter',
            field=models.PositiveIntegerField(default=310),
        ),
    ]
