# Generated by Django 3.2.14 on 2022-07-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_classattend_options_alter_classcancel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportSurveyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=6)),
                ('survey_counter', models.PositiveIntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
