# Generated by Django 3.2.14 on 2022-07-28 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20220728_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportersurvey',
            old_name='status',
            new_name='satisfaction',
        ),
        migrations.AddField(
            model_name='supportersurvey',
            name='validate_status',
            field=models.BooleanField(default=False),
        ),
    ]
