# Generated by Django 3.2.14 on 2022-07-29 08:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20220729_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinfo',
            name='counter',
            field=models.PositiveIntegerField(default=350, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(350)]),
        ),
    ]
