# Generated by Django 3.2.14 on 2022-07-23 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20220723_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classattend',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='classattend',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='classattend',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='classattend',
            name='ticket',
            field=models.CharField(max_length=10),
        ),
    ]
