# Generated by Django 3.2.14 on 2022-07-25 07:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20220723_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinfo',
            name='counter',
            field=models.PositiveIntegerField(default=310, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(310)]),
        ),
    ]
