version: "3.9"

services:
  django:
    build: .
    container_name: django
    command: gunicorn core.wsgi --bind 0.0.0.0:8000
    volumes:
      - ./core:/app
      - static_volume:/app/web/static
      - media_volume:/app/web/media
    expose:
      - "8000"
    environment:
      - SECRET_KEY=test
      - DEBUG=False
  
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    ports:
      - "80:80"
    depends_on:
      - django
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: CS50xIraq
 
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"


volumes:
  static_volume:
  media_volume:
